services:
  db:
    image: mongo:latest
    container_name: home-intranet-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    networks:
      - home-intranet-backend
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    ports:
      - 27017:27017
    volumes:
      - home-intranet-db-data:/data/db
    restart: unless-stopped

  backend:
    image: jameslanham/home-intranet-backend:latest
    container_name: home-intranet-backend
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}

      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_ALLOWED_HOSTS: ${BACKEND_ALLOWED_HOSTS}
      BACKEND_PROD_FLAG: ${BACKEND_PROD_FLAG}

      VIRTUAL_HOST: "api-stuff.intranet.local"
      VIRTUAL_PROTO: "http"
      VIRTUAL_PORT: 3000
    depends_on:
      - db
    networks:
      - home-intranet-backend
      - home-intranet-frontend
      - home-intranet-nginx
    restart: unless-stopped

  # frontend:
  #   image: jameslanham/home-intranet-frontend:latest
  #   container_name: home-intranet-frontend
  #   environment:
  #     API_URL: ${API_URL}
  #   depends_on:
  #     - backend
  #   networks:
  #     - home-intranet-frontend
  #     - home-intranet-nginx
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - "./Frontend/src:/app/src"
  #     - "./Frontend/tests:/app/tests"
  #     - "./Frontend/static:/app/static"
  #   restart: unless-stopped

networks:
  home-intranet-nginx:
    external: true
  home-intranet-backend:
    driver: bridge
  home-intranet-frontend:
    driver: bridge

volumes:
  home-intranet-db-data:
