name: Run Backend Unit Tests

on:
  pull_request:
    paths:
    - 'Backend/**'
    - '.github/workflows/backend-tests.yml'
    - '.github/workflows/backend-build.yml'
  push:
    branches: [ main ]
    paths:
    - 'Backend/**'
    - '.github/backend-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Tidy Go Modules
        run: go mod tidy
        working-directory: Backend

      - name: Test with the Go CLI
        run: go test -v ./...
        working-directory: Backend
