name: Build and Push Jenkins Docker Image

on:
    push:
      branches: [ main ]
      paths:
      - 'Jenkins/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push jenkins image
      uses: docker/build-push-action@v4
      with:
        context: ./Jenkins
        push: true
        tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/home-intranet-jenkins:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/home-intranet-jenkins:${{ github.run_number }}
